# This is a basic workflow that is manually triggered

name: Test workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      Environment:
        type: choice
        description: Environment
        required: true
        options:
        - PROD
        - INT
        - DEV
      runScript:
       type: string
       description: Script name
       required: true


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  RunSalesforceScripts:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest #změnit na csas-linux
    environment: Develop

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Salesforce SFDX CLI Action
      uses: sfdx-actions/setup-sfdx@v1

    - name: Checkout repository
      uses: actions/checkout@v2
            
    # Runs a single command using the runners shell
    - name: Authorize org
      env:
           SF_AUTH_URL: ${{ secrets.SF_AUTH_URL }}
           SFC_ORG: ${{ vars.SFC_ORG }} 
      run:  sf org login sfdx-url --alias ${SFC_ORG} --sfdx-url-file ${GITHUB_WORKSPACE}/URL/authFile.json
      
    - name: List orgs        
      run: sfdx force:org:list --all

    - name: runScript
      env: 
        SF_SCRIPT: ${{ inputs.runScript }}
      run: 
        sf apex run --target-org ${SFC_ORG} --file force-app/main/default/classes/accountCreator.cls
        
        
      
    
    
