name: Run Manual Apex

env:
  SF_DISABLE_DNS_CHECK: true
  SF_DISABLE_TELEMETRY: true
on:
  workflow_dispatch:
    inputs:
      ScriptPath:
       type: string
       description: Path to the script - e.g dev/scheduleJob.apex
       required: true
      environment:
        type: choice
        description: Environment to run the script in
        required: true
        options:
          - master
          - env/prs
          - env/int
          - env/dev


jobs:
  RunSalesforceScripts:
    runs-on: ubuntu-latest
    env:
      SF_AUTH_FILE: ${{ secrets.SF_AUTH_FILE }}  
      REF_NAME: ${{ github.ref_name }} 
      SFC_SCRIPT: ${{ inputs.ScriptPath }} 
      TARGET_ORG: ${{ inputs.Environment }}
    
    environment:
      name: ${TARGET_ORG}
    
    steps:
    - name: Choose ORG 
      run: echo "Target org =" ${TARGET_ORG}

    - name: Install tools
      run: npm i -g @salesforce/cli

    - name: Checkout repository   
      uses: actions/checkout@v2
            
    - name: Authorize org ${TARGET_ORG}
      env: 
        SFDX_AUTOMATION_AUTH_URL: ${{ secrets.SFDX_AUTOMATION_AUTH_URL }}
      run: sf org login sfdx-url --alias ${TARGET_ORG} --sfdx-url-stdin <<< "${{ secrets.SFDX_AUTH_URL }}" 
      
    - name: List org 
      run:    sf org list
      
    - name: runScript 
      run: 
        ${GITHUB_WORKSPACE}/scripts/${SFC_SCRIPT}
