name: Run Manual Apex

env:
  SF_DISABLE_DNS_CHECK: true
  SF_DISABLE_TELEMETRY: true
on:
  workflow_dispatch:
    inputs:
      ScriptPath:
       type: string
       description: Path to the script starting from folder scripts/apex/...
       required: true


jobs:
  RunSalesforceScripts:
    runs-on: ubuntu-latest
    env:
      SF_AUTH_FILE: ${{ secrets.SF_AUTH_FILE }}  
      REF_NAME: ${{ github.ref_name }} 
      SFC_SCRIPT: ${{ inputs.ScriptName }} 
    
    environment:
      name: ${{ github.ref_name }}
    
    steps:
    - name: Choose ORG 
      run: |
          TARGET_ORG=${REF_NAME#env/}
          printf "${TARGET_ORG}\n"
          echo "TARGET_ORG=${TARGET_ORG}" >>$GITHUB_ENV

    - name: Install tools
      run: npm i -g @salesforce/cli

    - name: Checkout repository   
      uses: actions/checkout@v2
            
    - name: Authorize org ${{ env.TARGET_ORG }}
      env: 
        SFDX_AUTOMATION_AUTH_URL: ${{ secrets.SFDX_AUTOMATION_AUTH_URL }}
        TARGET_ORG: ${{ env.TARGET_ORG }}
      run: sf org login sfdx-url --alias ${TARGET_ORG} --sfdx-url-stdin <<< "${{ secrets.SFDX_AUTH_URL }}" 
      
    - name: List org 
      run:    sf org list
      
    - name: runScript 
      env:
        TARGET_ORG: ${{ env.TARGET_ORG }}
      run: 
        sf apex run --target-org ${TARGET_ORG} --file ${GITHUB_WORKSPACE}/scripts/${SFC_SCRIPT}
