# This is a basic workflow that is manually triggered

name: Run Script on Org

env:
  SF_DISABLE_DNS_CHECK: true
  SF_DISABLE_TELEMETRY: true

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      ScriptName:
       type: string
       description: Script name
       required: true


jobs:
  RunSalesforceScripts:
    runs-on: ubuntu-latest
    env:
      SF_AUTH_FILE: ${{ secrets.SF_AUTH_FILE }}  
      REF_NAME: ${{ github.ref_name }} # Environment from input manual selection
      SFC_SCRIPT: ${{ inputs.ScriptName }} # String containing name of the script 
    
    environment:
      name: ${{ github.ref_name }}
    
    steps:
    - name: Choose ORG 
      run: |
          TARGET_ORG=${REF_NAME#env/}
          printf "${TARGET_ORG}\n"
          echo "TARGET_ORG=${TARGET_ORG}" >>$GITHUB_ENV
      
 
        
        
      
    
    
