name: Run Manual Apex

env:
  SF_DISABLE_DNS_CHECK: true
  SF_DISABLE_TELEMETRY: true
on:
  workflow_dispatch:
    inputs:
      ScriptPath:
       type: string
       description: Path to the script - e.g dev/scheduleJob.apex
       required: true
      environment:
        type: choice
        description: Environment to run the script in
        required: true
        options:
          - master
          - env/prs
          - env/int
          - env/dev


jobs:
  RunSalesforceScripts:
    runs-on: ubuntu-latest
    env:
      REF_NAME: ${{ github.ref_name }} 
      SFC_SCRIPT: ${{ inputs.ScriptPath }} 
      TARGET_ORG: ${{ inputs.Environment }}
    
    environment:
      name: ${TARGET_ORG}
    
    steps:
    - name: Choose ORG 
      run: echo "Target org =" ${TARGET_ORG} >>$GITHUB_ENV

    - name: Install tools
      run: npm i -g @salesforce/cli

    - name: Checkout repository   
      uses: actions/checkout@v2
      
    - name: echo
      run: echo ${{ env.TARGET_ORG }}
      
    - name: Authorize org ${{ env.TARGET_ORG }}
      env: 
        TARGET_ORG: ${{ env.TARGET_ORG }}
        SFDX_AUTOMATION_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        VAR_TARGET_ORG_ECHO: ${{ vars.VAR_TARGET_ORG }} 
      run: sf org login sfdx-url --alias ${TARGET_ORG} --sfdx-url-stdin <<< "${SFDX_AUTOMATION_AUTH_URL}" 
      
    - name: List org 
      run:    sf org list
      
    - name: runScript 
      run: 
        ${GITHUB_WORKSPACE}/scripts/${SFC_SCRIPT}
