# This is a basic workflow that is manually triggered

name: Run Script on Org

env:
  SF_DISABLE_DNS_CHECK: true
  SF_DISABLE_TELEMETRY: true

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      Org:
        type: choice
        description: Org where to run
        required: true
        options:
        - INT
        - DEV
      ScriptName:
       type: string
       description: Script name
       required: true


jobs:
  RunSalesforceScripts:
    runs-on: ubuntu-latest
    env:
      SF_AUTH_FILE: ${{ secrets.SF_AUTH_FILE }}  
      SFC_ORG: ${{ inputs.Org }} # Environment from input manual selection
      SFC_SCRIPT: ${{ inputs.ScriptName }} # String containing name of the script 
    
    environment:
      name: ${{ github.ref_name }}

    steps:
 #   name: Salesforce SFDX CLI Action Install sfdx as prerequsity to run sfdx commands
  #    uses: sfdx-actions/setup-sfdx@v1
     
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        registry-url: "https://npm.pkg.github.com"

    - name: Install tools
      run: npm i -g @salesforce/cli

    - name: Checkout repository   # loading folders and files in repo 
      uses: actions/checkout@v2
            
    - name: Authorize org 
      run: sf org login sfdx-url --sfdx-url-stdin <<< "${{ secrets.SFDX_AUTH_URL }}" --alias ${SFC_ORG}
      
    - name: List org # check if the authorized org is succesfull
      run:    sf org list
      
    - name: runScript 
      run: 
        sf apex run --target-org ${SFC_ORG} --file ${GITHUB_WORKSPACE}/scripts/${SF_SCRIPT}
        
        
      
    
    
