# This is a basic workflow that is manually triggered

name: Run Script on Org

env:
  SF_DISABLE_DNS_CHECK: true
  SF_DISABLE_TELEMETRY: true

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      ScriptName:
       type: string
       description: Script name
       required: true


jobs:
  RunSalesforceScripts:
    runs-on: ubuntu-latest
    env:
      SF_AUTH_FILE: ${{ secrets.SF_AUTH_FILE }}  
      SFC_ORG: ${{ github.ref_name }} # Environment from input manual selection
      SFC_SCRIPT: ${{ inputs.ScriptName }} # String containing name of the script 
    
    environment:
      name: ${{ github.ref_name }}
    
    steps:
    - name: Choose ORG 
      -run: |
          TARGET_ORG=${REF_NAME#env/}
          printf "${TARGET_ORG}\n"
          echo "TARGET_ORG=${TARGET_ORG}" >>$GITHUB_ENV
      
    - name: Install tools
      run: npm i -g @salesforce/cli

    - name: Checkout repository   # loading folders and files in repo 
      uses: actions/checkout@v2
            
    - name: Authorize org 
      run: sf org login sfdx-url --alias ${SFC_ORG} --sfdx-url-stdin <<< "${{ secrets.SFDX_AUTH_URL }}" 
      
    - name: List org # check if the authorized org is succesfull
      run:    sf org list

    - name: Checkout master branch
      uses: actions/checkout@v3
      with:
        ref: master
        path: master_branch
    - name: Access ManualSteps folder
      run: |
        cp -r master_branch/scripts ./ManualSteps
      
    - name: runScript 
      run: 
        sf apex run --target-org ${SFC_ORG} --file ${GITHUB_WORKSPACE}/scripts/${SFC_SCRIPT}
        
        
      
    
    
