# This is a basic workflow that is manually triggered

name: Test 2.0 workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      Org:
        type: choice
        description: Org where to run
        required: true
        options:
        - PROD
        - INT
        - DEV
      ScriptName:
       type: string
       description: Script name
       required: true


jobs:
  RunSalesforceScripts:
    runs-on: ubuntu-latest #změnit na csas-linux
    environment:
      name: ${{ github.ref_name }}
    env:
      SF_AUTH_FILE: ${{ secrets.SF_AUTH_FILE }}
      SFC_ORG: ${{ inputs.Org }} 
      SFC_SCRIPT: ${{ inputs.ScriptName }}

    steps:
    - name: Show actual branch
      run:  echo "Actual environment =  ${{ github.ref_name }}  Env Var=  ${{ vars.TEST_VARIABLE }} " 
   
        
        
      
    
    
