# This is a basic workflow that is manually triggered

name: Test 2.0 workflow
env:
  SF_DISABLE_DNS_CHECK: true
  SF_DISABLE_TELEMETRY: true
on:
  workflow_dispatch:
    inputs:
      ScriptPath:
       type: string
       description: Path to the script - e.g dev/scheduleJob.apex
       required: true
      environment:
        type: choice
        description: Environment to run the script in
        required: true
        options:
          - master
          - Develop
          - env/int
          - env/dev


jobs:
  RunSalesforceScripts:
    runs-on: ubuntu-latest
    env:
      REF_NAME: ${{ github.ref_name }} 
      SFC_SCRIPT: ${{ inputs.ScriptPath }} 
      INPUT_ENVIRONMENT: ${{ inputs.Environment}}
    
    environment:
      name: ${{ inputs.Environment }}
    
    steps:      
    - name: Choose target ORG
      run: | 
          TARGET_ORG=${INPUT_ENVIRONMENT#env/}
          echo "TARGET_ORG=${TARGET_ORG}" >>$GITHUB_ENV

    - name: Install tools
      run: npm i -g @salesforce/cli

    - name: Checkout repository   
      uses: actions/checkout@v2
      
    - name: echo
      run: echo ${{ env.TARGET_ORG }} "and" ${TARGET_ORG}
      
    - name: Authorize org ${{ env.TARGET_ORG }}
      env: 
        TARGET_ORG: ${{ env.TARGET_ORG }}
        SFDX_AUTOMATION_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
      run: sf org login sfdx-url --alias ${TARGET_ORG} --sfdx-url-stdin <<< ${{ secrets.SFDX_AUTH_URL }} 
   
        
        
      
    
    
