# This is a basic workflow that is manually triggered

name: Echo Variables

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      Environment:
        type: choice
        description: Environment
        required: true
        options:
        - PROD
        - INT
        - DEV
        
      runScript:
       type: string
       description: scriptName
       required: true


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  RunSalesforceScripts:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest #změnit na csas-linux
    environment: ${{inputs.environment}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:          
    # Runs a single command using the runners shell
    - name: Authorize org
      env:
           SF_AUTH_URL: ${{ secrets.SF_AUTH_URL }}
           SFC_ORG: ${{ vars.SFC_ORG }} 
      run: echo "SFC_ORG = ${SFC_ORG}" /n
           echo "${{inputs.scriptName}}
  
        
        
      
    
    
