# This is a basic workflow that is manually triggered

name: Echo Variables

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: 'Branch to run the workflow on'
        required: true

        
      runScript:
       type: string
       description: scriptName
       required: true


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-on-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Run a script
        run: echo "Running on branch ${{ github.event.inputs.branch }}"
